name: test

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  verify_job:
    runs-on: ubuntu-latest
    container:
      image:  maven:3-jdk-8-slim
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: ./gradlew --version